
export const APP_NAME = "Wilbe";

export const PATHS = {
  HOME: "/",
  KNOWLEDGE_CENTER: "/knowledge-center",
  MEMBER_DIRECTORY: "/member-directory",
  VIDEO: "/video",
  BUILD_YOUR_DECK: "/build-your-deck",
  LAB_SEARCH: "/lab-search",
  EVENTS: "/events",
  ASK: "/ask",
  ADMIN: "/admin",
  PROFILE: "/profile",
  REGISTER: "/register",
  LOGIN: "/login",
  PENDING: "/pending",
  LANDING_PAGE: "/landing-page",
  BSF_PAGE: "/bsf"
};

export const NAV_ITEMS = [
  { name: "Home", path: PATHS.HOME },
  { name: "Knowledge Center", path: PATHS.KNOWLEDGE_CENTER },
  { name: "Member Directory", path: PATHS.MEMBER_DIRECTORY },
  { name: "Build Your Deck", path: PATHS.BUILD_YOUR_DECK },
  { name: "Lab Search", path: PATHS.LAB_SEARCH },
  { name: "Events", path: PATHS.EVENTS },
  { name: "Ask & Invite", path: PATHS.ASK },
];

export const MODULES = [
  {
    id: "startup-founder",
    title: "Startup Founder",
    slug: "startup-founder",
    description: "Learn the essentials of founding a startup",
    videos: []
  },
  {
    id: "entrepreneurial-pi",
    title: "Entrepreneurial PI",
    slug: "entrepreneurial-pi",
    description: "Insights for entrepreneurial principal investigators",
    videos: []
  },
  {
    id: "scientist-at-startup",
    title: "Scientist at Startup",
    slug: "scientist-at-startup",
    description: "Guide for scientists working in startups",
    videos: []
  },
  {
    id: "product-manager",
    title: "Product Manager",
    slug: "product-manager",
    description: "Product management in science-based businesses",
    videos: []
  }
];

export const VIDEOS = [
  {
    id: "1",
    moduleId: "startup-founder",
    title: "Conversations at the Crossroads: Navigating Technological and Societal Forces",
    description: "Dive into the mind of Albert Wenger from Union Square Ventures! A must-hear for scientists and thinkers aiming to understand the intersections of innovation and society.",
    youtubeId: "example1",
    duration: "27:51",
    order: 1,
    presenter: "Albert Wenger",
    thumbnailUrl: "/lovable-uploads/e63aae6f-8753-4509-aff4-323cac4af598.png",
  },
  {
    id: "2",
    moduleId: "entrepreneurial-pi",
    title: "The Entrepreneurial Mindset: An Insider's Guide",
    description: "Ex-Google and Google-X Executive Chris O'Neill share his nuggets of wisdom of the powerful Bay Area entrepreneurial mindset.",
    youtubeId: "example2",
    duration: "47:00",
    order: 1,
    presenter: "Chris O'Neill",
    thumbnailUrl: "/lovable-uploads/86efc3b2-8104-4252-9196-0b3226d6247a.png",
  },
  {
    id: "3",
    moduleId: "scientist-at-startup",
    title: "Building the Future of Science: The Arcadia Way with Prachee Avasthi",
    description: "Prachee and Ale discuss the dynamic interplay between academic freedom and industry innovation.",
    youtubeId: "example3",
    duration: "35:51",
    order: 1,
    presenter: "Prachee Avasthi",
    thumbnailUrl: "/lovable-uploads/210c5ab3-0cd0-4587-a643-df2b47e5ab1e.png",
  },
  {
    id: "4",
    moduleId: "product-manager",
    title: "From Physician to Founder: A Career Path Driven by a Vision for Better Healthcare",
    description: "Jordan discusses his motivation to move from clinical practice to business, the challenges he faced, and the vision behind Uploid.",
    youtubeId: "example4",
    duration: "6:12",
    order: 1,
    presenter: "Jordan Abdi",
    thumbnailUrl: "/lovable-uploads/783800c2-496d-4441-b067-52820a7f1ad8.png",
  },
  {
    id: "5",
    moduleId: "scientist-at-startup",
    title: "Working as a Scientist at a Diagnostics Startup",
    description: "Learn about the unique challenges and opportunities of working as a scientist in a diagnostic startup.",
    youtubeId: "example5",
    duration: "8:51",
    order: 2,
    presenter: "Giulia Pilla",
    thumbnailUrl: "/lovable-uploads/210c5ab3-0cd0-4587-a643-df2b47e5ab1e.png",
  },
  {
    id: "6",
    moduleId: "scientist-at-startup",
    title: "Career Paths in Biotech: Nimish's Insider Story",
    description: "Discover various career trajectories in the biotech industry through Nimish's personal journey.",
    youtubeId: "example6",
    duration: "52:22",
    order: 3,
    presenter: "Nimish Gera",
    thumbnailUrl: "/lovable-uploads/e63aae6f-8753-4509-aff4-323cac4af598.png",
  }
];

export const SAMPLE_USERS = [
  {
    id: "1",
    firstName: "Matthew",
    lastName: "Staitis",
    email: "matthew.staitis@example.com",
    linkedIn: "https://linkedin.com/in/matthewstaitis",
    institution: "University of East Anglia",
    location: "Norwich, UK",
    role: "Palaeoclimatology | Micropalaeontology | Geochemistry",
    bio: "I am a geoscientist that utilizes litho-, bio-, and chemostratigraphy to identify and investigate the biotic and environmental changes during abrupt climate change in the geological record.",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: "2",
    firstName: "Toomas Erik",
    lastName: "Anjärv",
    email: "toomas.anjarv@example.com",
    linkedIn: "https://linkedin.com/in/toomasanjarv",
    institution: "Lund University",
    location: "Lund, Sweden",
    role: "Neuroimaging (MRI, PET, EEG) | Data Science (Python, Julia, MATLAB)",
    bio: "I'm a PhD student in the field of neuroimaging and neurodegenerative diseases at the Clinical Memory Research Unit.",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    id: "3",
    firstName: "Alfredo",
    lastName: "Fantetti",
    email: "alfredo.fantetti@example.com",
    linkedIn: "https://linkedin.com/in/alfredofantetti",
    institution: "Imperial College London",
    location: "London, UK",
    role: "Mechanical Engineering",
    bio: "Researcher and Tech Enterpeneur",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
  },
  {
    id: "4",
    firstName: "Emma",
    lastName: "Davis",
    email: "emma.davis@example.com",
    linkedIn: "https://linkedin.com/in/emmadavis",
    institution: "UK Dementia Research Institute & Francis Crick",
    location: "London, United Kingdom",
    role: "Bioinformatician",
    bio: "Final year bioinformatics PhD student interested in leveraging ML for neurodegeneration drug discovery in SE England",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: "5",
    firstName: "Daniel",
    lastName: "Wilinski",
    email: "daniel.wilinski@example.com",
    linkedIn: "https://linkedin.com/in/danielwilinski",
    institution: "stealth",
    location: "Ann Arbor, USA",
    role: "Scientist",
    bio: "As a molecular biologist focused on diabetes research, I'm drawn to Wilbe's mission of bridging scientific innovation with industry applications.",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
  },
];
