
export const SAMPLE_USERS = [
  {
    id: "1",
    firstName: "Matthew",
    lastName: "Staitis",
    email: "matthew.staitis@example.com",
    linkedIn: "https://linkedin.com/in/matthewstaitis",
    institution: "University of East Anglia",
    location: "Norwich, UK",
    role: "Palaeoclimatology | Micropalaeontology | Geochemistry",
    bio: "I am a geoscientist that utilizes litho-, bio-, and chemostratigraphy to identify and investigate the biotic and environmental changes during abrupt climate change in the geological record.",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: "2",
    firstName: "Toomas Erik",
    lastName: "Anjärv",
    email: "toomas.anjarv@example.com",
    linkedIn: "https://linkedin.com/in/toomasanjarv",
    institution: "Lund University",
    location: "Lund, Sweden",
    role: "Neuroimaging (MRI, PET, EEG) | Data Science (Python, Julia, MATLAB)",
    bio: "I'm a PhD student in the field of neuroimaging and neurodegenerative diseases at the Clinical Memory Research Unit.",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    id: "3",
    firstName: "Alfredo",
    lastName: "Fantetti",
    email: "alfredo.fantetti@example.com",
    linkedIn: "https://linkedin.com/in/alfredofantetti",
    institution: "Imperial College London",
    location: "London, UK",
    role: "Mechanical Engineering",
    bio: "Researcher and Tech Enterpeneur",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
  },
  {
    id: "4",
    firstName: "Emma",
    lastName: "Davis",
    email: "emma.davis@example.com",
    linkedIn: "https://linkedin.com/in/emmadavis",
    institution: "UK Dementia Research Institute & Francis Crick",
    location: "London, United Kingdom",
    role: "Bioinformatician",
    bio: "Final year bioinformatics PhD student interested in leveraging ML for neurodegeneration drug discovery in SE England",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: "5",
    firstName: "Daniel",
    lastName: "Wilinski",
    email: "daniel.wilinski@example.com",
    linkedIn: "https://linkedin.com/in/danielwilinski",
    institution: "stealth",
    location: "Ann Arbor, USA",
    role: "Scientist",
    bio: "As a molecular biologist focused on diabetes research, I'm drawn to Wilbe's mission of bridging scientific innovation with industry applications.",
    approved: true,
    createdAt: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
  },
];
