
export const VIDEOS = [
  {
    id: "1",
    moduleId: "startup-founder",
    title: "Conversations at the Crossroads: Navigating Technological and Societal Forces",
    description: "Dive into the mind of Albert Wenger from Union Square Ventures! A must-hear for scientists and thinkers aiming to understand the intersections of innovation and society.",
    youtubeId: "example1",
    duration: "27:51",
    order: 1,
    presenter: "Albert Wenger",
    thumbnailUrl: "/lovable-uploads/e63aae6f-8753-4509-aff4-323cac4af598.png",
  },
  {
    id: "2",
    moduleId: "entrepreneurial-pi",
    title: "The Entrepreneurial Mindset: An Insider's Guide",
    description: "Ex-Google and Google-X Executive Chris O'Neill share his nuggets of wisdom of the powerful Bay Area entrepreneurial mindset.",
    youtubeId: "example2",
    duration: "47:00",
    order: 1,
    presenter: "Chris O'Neill",
    thumbnailUrl: "/lovable-uploads/86efc3b2-8104-4252-9196-0b3226d6247a.png",
  },
  {
    id: "3",
    moduleId: "scientist-at-startup",
    title: "Building the Future of Science: The Arcadia Way with Prachee Avasthi",
    description: "Prachee and Ale discuss the dynamic interplay between academic freedom and industry innovation.",
    youtubeId: "example3",
    duration: "35:51",
    order: 1,
    presenter: "Prachee Avasthi",
    thumbnailUrl: "/lovable-uploads/210c5ab3-0cd0-4587-a643-df2b47e5ab1e.png",
  },
  {
    id: "4",
    moduleId: "product-manager",
    title: "From Physician to Founder: A Career Path Driven by a Vision for Better Healthcare",
    description: "Jordan discusses his motivation to move from clinical practice to business, the challenges he faced, and the vision behind Uploid.",
    youtubeId: "example4",
    duration: "6:12",
    order: 1,
    presenter: "Jordan Abdi",
    thumbnailUrl: "/lovable-uploads/783800c2-496d-4441-b067-52820a7f1ad8.png",
  },
  {
    id: "5",
    moduleId: "scientist-at-startup",
    title: "Working as a Scientist at a Diagnostics Startup",
    description: "Learn about the unique challenges and opportunities of working as a scientist in a diagnostic startup.",
    youtubeId: "example5",
    duration: "8:51",
    order: 2,
    presenter: "Giulia Pilla",
    thumbnailUrl: "/lovable-uploads/210c5ab3-0cd0-4587-a643-df2b47e5ab1e.png",
  },
  {
    id: "6",
    moduleId: "scientist-at-startup",
    title: "Career Paths in Biotech: Nimish's Insider Story",
    description: "Discover various career trajectories in the biotech industry through Nimish's personal journey.",
    youtubeId: "example6",
    duration: "52:22",
    order: 3,
    presenter: "Nimish Gera",
    thumbnailUrl: "/lovable-uploads/e63aae6f-8753-4509-aff4-323cac4af598.png",
  }
];
